'use client'
import { useEffect, useState } from 'react'
import RichEditor from '@/components/RichEditor'
import Uploader from '@/components/Uploader'

function Field({label, children}){ return <label><span className="label">{label}</span>{children}</label> }
const initialBlog={title:'',category:'Legal Intelligence',excerpt:'',content:'',featuredImage:'',imageSize:'large',status:'published'}
const initialCourse={title:'',description:'',thumbnail:'',introVideo:'',pdfUrl:'',audioUrl:'',imageSize:'medium',modulesText:'Introduction\nCore Concepts\nPractical Examples\nRevision Notes\nAssessment'}
const initialMedia={title:'',category:'Court Visits',type:'image',url:'',description:'',size:'medium'}

export default function AdminPage(){
 const [auth,setAuth]=useState(false), [login,setLogin]=useState({email:'',password:''}), [msg,setMsg]=useState('')
 const [blog,setBlog]=useState(initialBlog), [course,setCourse]=useState(initialCourse), [media,setMedia]=useState(initialMedia)
 const [enrollments,setEnrollments]=useState([]), [contacts,setContacts]=useState([])
 async function doLogin(e){ e.preventDefault(); const res=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)}); const data=await res.json(); setMsg(data.message||''); if(data.success){setAuth(true); loadData()} }
 async function loadData(){ const [e,c]=await Promise.all([fetch('/api/enrollments').then(r=>r.json()).catch(()=>({})), fetch('/api/contacts').then(r=>r.json()).catch(()=>({}))]); setEnrollments(e.enrollments||[]); setContacts(c.contacts||[]) }
 async function save(type,payload,reset){ const res=await fetch(`/api/${type}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const data=await res.json(); setMsg(data.success?'Saved successfully':data.message||'Save failed'); if(data.success) reset(); }
 if(!auth) return <main className="section"><div className="container max-w-lg"><form onSubmit={doLogin} className="card p-8"><h1 className="font-display text-4xl gold-text">Admin Login</h1><p className="mt-2 text-sm text-ivory/65">Enter secure admin credentials to manage website content.</p><div className="mt-6 grid gap-4"><input className="input" placeholder="Admin email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><input type="password" className="input" placeholder="Enter admin password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button className="btn-gold">Login</button>{msg&&<p className="text-sm text-gold-300">{msg}</p>}</div></form></div></main>
 return <main className="section"><div className="container"><div className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><p className="section-kicker">Secure Admin Dashboard</p><h1 className="section-title mt-2">Content Management</h1></div><button onClick={()=>fetch('/api/admin/logout',{method:'POST'}).then(()=>location.reload())} className="btn-outline">Logout</button></div>{msg&&<div className="mb-6 rounded-2xl border border-gold-500/25 bg-gold-500/10 p-4 text-gold-200">{msg}</div>}
 <div className="admin-grid">
  <form className="card p-6" onSubmit={e=>{e.preventDefault(); save('blogs',blog,()=>setBlog(initialBlog))}}><h2 className="font-display text-3xl gold-text">Create Blog</h2><div className="mt-5 grid gap-4"><Field label="Title"><input className="input" value={blog.title} onChange={e=>setBlog({...blog,title:e.target.value})}/></Field><Field label="Category"><input className="input" value={blog.category} onChange={e=>setBlog({...blog,category:e.target.value})}/></Field><Field label="Featured Image"><Uploader folder="nyayasutra/blog" onUploaded={url=>setBlog({...blog,featuredImage:url})}/><input className="input mt-2" placeholder="or paste image URL" value={blog.featuredImage} onChange={e=>setBlog({...blog,featuredImage:e.target.value})}/></Field><Field label="Image Size"><select className="input" value={blog.imageSize} onChange={e=>setBlog({...blog,imageSize:e.target.value})}><option>small</option><option>medium</option><option>large</option></select></Field><Field label="Excerpt"><textarea className="input min-h-24" value={blog.excerpt} onChange={e=>setBlog({...blog,excerpt:e.target.value})}/></Field><Field label="Full Content Formatting"><RichEditor value={blog.content} onChange={content=>setBlog({...blog,content})}/></Field><button className="btn-gold">Save Blog</button></div></form>
  <form className="card p-6" onSubmit={e=>{e.preventDefault(); save('courses',course,()=>setCourse(initialCourse))}}><h2 className="font-display text-3xl gold-text">Create Course</h2><div className="mt-5 grid gap-4"><Field label="Course Title"><input className="input" value={course.title} onChange={e=>setCourse({...course,title:e.target.value})}/></Field><Field label="Description"><textarea className="input min-h-24" value={course.description} onChange={e=>setCourse({...course,description:e.target.value})}/></Field><Field label="Thumbnail Upload"><Uploader folder="nyayasutra/courses" onUploaded={url=>setCourse({...course,thumbnail:url})}/><input className="input mt-2" placeholder="or paste thumbnail URL" value={course.thumbnail} onChange={e=>setCourse({...course,thumbnail:e.target.value})}/></Field><Field label="Image Size"><select className="input" value={course.imageSize} onChange={e=>setCourse({...course,imageSize:e.target.value})}><option>small</option><option>medium</option><option>large</option></select></Field><Field label="YouTube / Intro Video URL"><input className="input" value={course.introVideo} onChange={e=>setCourse({...course,introVideo:e.target.value})}/></Field><Field label="PDF Material Upload"><Uploader folder="nyayasutra/course-pdf" onUploaded={url=>setCourse({...course,pdfUrl:url})}/><input className="input mt-2" placeholder="or paste PDF URL" value={course.pdfUrl} onChange={e=>setCourse({...course,pdfUrl:e.target.value})}/></Field><Field label="Audio Material Upload"><Uploader folder="nyayasutra/course-audio" onUploaded={url=>setCourse({...course,audioUrl:url})}/><input className="input mt-2" placeholder="or paste audio URL" value={course.audioUrl} onChange={e=>setCourse({...course,audioUrl:e.target.value})}/></Field><Field label="Course Modules, one per line"><textarea className="input min-h-36" value={course.modulesText} onChange={e=>setCourse({...course,modulesText:e.target.value})}/></Field><button className="btn-gold">Save Course</button></div></form>
  <form className="card p-6" onSubmit={e=>{e.preventDefault(); save('gallery',media,()=>setMedia(initialMedia))}}><h2 className="font-display text-3xl gold-text">Add Gallery/Media</h2><div className="mt-5 grid gap-4"><Field label="Title"><input className="input" value={media.title} onChange={e=>setMedia({...media,title:e.target.value})}/></Field><Field label="Category"><input className="input" value={media.category} onChange={e=>setMedia({...media,category:e.target.value})}/></Field><Field label="Type"><select className="input" value={media.type} onChange={e=>setMedia({...media,type:e.target.value})}><option>image</option><option>video</option><option>audio</option><option>pdf</option></select></Field><Field label="Upload Media"><Uploader folder="nyayasutra/gallery" onUploaded={url=>setMedia({...media,url})}/><input className="input mt-2" placeholder="or paste URL / YouTube / Cloudinary URL" value={media.url} onChange={e=>setMedia({...media,url:e.target.value})}/></Field><Field label="Display Size"><select className="input" value={media.size} onChange={e=>setMedia({...media,size:e.target.value})}><option>small</option><option>medium</option><option>large</option></select></Field><Field label="Description"><textarea className="input min-h-24" value={media.description} onChange={e=>setMedia({...media,description:e.target.value})}/></Field><button className="btn-gold">Save Media</button></div></form>
 </div>
 <section className="mt-10 grid gap-8 lg:grid-cols-2"><div className="card p-6"><h2 className="font-display text-3xl gold-text">Student Enrollments</h2><button onClick={loadData} className="btn-outline mt-4">Refresh Data</button><div className="mt-5 grid gap-3">{enrollments.map((e,i)=><div key={i} className="rounded-2xl bg-white/5 p-4 text-sm"><b>{e.name}</b> — {e.courseTitle}<br/>{e.phone} {e.email}</div>)}{!enrollments.length&&<p className="text-ivory/60">No enrollments yet.</p>}</div></div><div className="card p-6"><h2 className="font-display text-3xl gold-text">Contact Queries</h2><button onClick={loadData} className="btn-outline mt-4">Refresh Data</button><div className="mt-5 grid gap-3">{contacts.map((c,i)=><div key={i} className="rounded-2xl bg-white/5 p-4 text-sm"><b>{c.name}</b> — {c.service}<br/>{c.phone} {c.email}<p>{c.message}</p></div>)}{!contacts.length&&<p className="text-ivory/60">No queries yet.</p>}</div></div></section>
 </div></main>
}
